In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Lasso, LassoCV, Ridge, RidgeCV, ElasticNet, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from pandas_profiling import ProfileReport
from sklearn.preprocessing import StandardScaler

In [17]:
df = pd.read_excel(r"C:\Users\ts-sachin.bhumihar\Downloads\Real estate valuation data set.xlsx")

In [18]:
df.head()

No  X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude  Y house price of unit area
0   1          2012.916667          32.0  ...     24.98298     121.54024                        37.9
1   2          2012.916667          19.5  ...     24.98034     121.53951                        42.2
2   3          2013.583333          13.3  ...     24.98746     121.54391                        47.3
3   4          2013.500000          13.3  ...     24.98746     121.54391                        54.8
4   5          2012.833333           5.0  ...     24.97937     121.54245                        43.1

[5 rows x 8 columns]

In [19]:
df.tail()

No  X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude  Y house price of unit area
409  410          2013.000000          13.7  ...     24.94155     121.50381                        15.4
410  411          2012.666667           5.6  ...     24.97433     121.54310                        50.0
411  412          2013.250000          18.8  ...     24.97923     121.53986                        40.6
412  413          2013.000000           8.1  ...     24.96674     121.54067                        52.5
413  414          2013.500000           6.5  ...     24.97433     121.54310                        63.9

[5 rows x 8 columns]

In [21]:
df.drop(columns = "No", inplace = True)

In [22]:
df.head(2)

X1 transaction date  X2 house age  ...  X6 longitude  Y house price of unit area
0          2012.916667          32.0  ...     121.54024                        37.9
1          2012.916667          19.5  ...     121.53951                        42.2

[2 rows x 7 columns]

In [23]:
df.isnull().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [24]:
df.dtypes

X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

In [25]:
pf = ProfileReport(df)

In [26]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [28]:
df.head(2)

X1 transaction date  X2 house age  ...  X6 longitude  Y house price of unit area
0          2012.916667          32.0  ...     121.54024                        37.9
1          2012.916667          19.5  ...     121.53951                        42.2

[2 rows x 7 columns]

In [29]:
y = df["Y house price of unit area"]

In [30]:
y.head(1)

0    37.9
Name: Y house price of unit area, dtype: float64

In [31]:
x = df.drop(columns = "Y house price of unit area")

In [32]:
x.head(1)

X1 transaction date  X2 house age  ...  X5 latitude  X6 longitude
0          2012.916667          32.0  ...     24.98298     121.54024

[1 rows x 6 columns]

In [34]:
df.shape

(414, 7)

In [35]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [36]:
vif_df = pd.DataFrame()

In [39]:
scaler = StandardScaler()

In [40]:
arr = scaler.fit_transform(x)

In [41]:
arr

array([[-0.82472165,  1.25562833, -0.79249504,  2.00740743,  1.12542986,
         0.44876222],
       [-0.82472165,  0.15708622, -0.61661163,  1.66750286,  0.91244418,
         0.40113894],
       [ 1.54224386, -0.38779067, -0.41401527,  0.30788458,  1.48686011,
         0.68818339],
       ...,
       [ 0.35876111,  0.09556786, -0.54967846,  0.98769372,  0.82289338,
         0.42397202],
       [-0.52885105, -0.84478419, -0.77668389,  0.30788458, -0.18475479,
         0.4768143 ],
       [ 1.24637326, -0.98539758, -0.78807071,  1.66750286,  0.42757905,
         0.63534112]])

In [42]:
arr.shape

(414, 6)

In [43]:
vif_df["vif"] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [44]:
vif_df["feature"] = x.columns

In [45]:
vif_df

vif                                 feature
0  1.014655                     X1 transaction date
1  1.014287                            X2 house age
2  4.322984  X3 distance to the nearest MRT station
3  1.617021         X4 number of convenience stores
4  1.610225                             X5 latitude
5  2.926305                            X6 longitude

In [46]:
x_train, x_test, y_train, y_test = train_test_split(arr, y, test_size=0.24, random_state=34)

In [47]:
x_train

array([[-0.52885105, -0.7744775 ,  1.58203634, -1.39163828, -1.16093917,
         2.14689108],
       [-1.71233381, -0.19444726, -0.21256355, -0.03202   ,  0.79304312,
         0.08343293],
       [ 1.24637326, -0.36142566, -0.60671455,  0.64778915, -0.32916554,
         0.61381278],
       ...,
       [ 0.95050266, -0.11535223, -0.55058891,  0.64778915, -0.39612695,
         0.61120329],
       [-0.23298045,  2.081732  , -0.63675284,  1.32759829,  0.35658382,
         0.49377601],
       [ 0.35876111,  1.21168664, -0.53065713, -0.03202   ,  1.04556023,
         0.73580667]])

In [48]:
x_test

array([[ 9.50502663e-01, -8.53572528e-01, -7.54680765e-01,
         1.66750286e+00,  1.12542986e+00,  4.20710154e-01],
       [-1.12059261e+00, -1.76870587e-01, -2.12563547e-01,
        -3.20199958e-02,  7.93043116e-01,  8.34329289e-02],
       [-2.32980449e-01, -3.26272314e-01, -5.11694731e-01,
        -1.05173371e+00,  4.75984884e-01, -3.95409398e-01],
       [ 9.50502663e-01,  1.38745338e+00,  7.09817859e-01,
        -7.11829138e-01,  1.42877311e+00, -9.73412534e-01],
       [ 6.54631707e-01,  1.71262185e+00, -7.11872682e-01,
         1.66750286e+00,  6.45405314e-01,  6.05984297e-01],
       [ 6.54631707e-01, -3.35060651e-01, -6.30311542e-01,
         3.07884575e-01,  1.04878729e+00,  6.60131318e-01],
       [ 9.50502663e-01, -2.74688598e-02, -6.99122485e-02,
        -1.39163828e+00, -4.82450688e-01,  1.03002723e+00],
       [ 1.24637326e+00, -1.19631767e+00, -6.11612675e-01,
         3.07884575e-01, -1.05848015e+00,  4.04400810e-01],
       [ 1.24637326e+00, -1.20510600e+00,  8.436

In [49]:
y_train

187    22.0
159    37.4
137    47.4
158    39.4
377    56.8
       ... 
324    31.3
85     50.8
246    40.6
361    63.3
122    32.5
Name: Y house price of unit area, Length: 314, dtype: float64

In [50]:
y_test

381    47.3
265    38.1
179    42.6
283    23.5
220    78.3
       ... 
208    26.2
127    55.0
32     34.2
189    20.5
254    51.8
Name: Y house price of unit area, Length: 100, dtype: float64

In [51]:
reg = LinearRegression()

In [52]:
reg.fit(x_train, y_train)

LinearRegression()

In [53]:
reg.score(x_train, y_train)

0.5626558290181947

In [54]:
reg.score(x_test, y_test)

0.6478907490595796

In [56]:
df.head(2)

X1 transaction date  X2 house age  ...  X6 longitude  Y house price of unit area
0          2012.916667          32.0  ...     121.54024                        37.9
1          2012.916667          19.5  ...     121.53951                        42.2

[2 rows x 7 columns]

In [58]:
test1 = scaler.transform([[2012.916667, 32.0, 84.87882, 10, 24.98298, 121.54024]])

In [59]:
reg.predict(test1)

array([45.9344743])

In [60]:
# Let's create a function for adjusted r2 for test data set
def adj1_r2(x,y):
    r2 = reg.score(x_test, y_test)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = (1-(1-r2)*(n-1)/(n-p-1))
    return adjusted_r2


In [61]:
adj1_r2(x_test, y_test)

0.6251740231924556