In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Lasso, LassoCV, Ridge, RidgeCV, ElasticNet, ElasticNetCV, LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from pandas_profiling import ProfileReport

In [2]:
df = pd.read_csv(r"C:\Users\ts-sachin.bhumihar\Downloads\Linear Regression live coding demonstration part 1-20221109T123500Z-001\Linear Regression live coding demonstration part 1\advertising.csv")

In [3]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [5]:
df.shape

(200, 4)

In [6]:
pf = ProfileReport(df)

In [7]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
df.head(2)

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4

In [10]:
Y = df['Sales']

In [11]:
Y.head()

0    22.1
1    10.4
2    12.0
3    16.5
4    17.9
Name: Sales, dtype: float64

In [12]:
X = df.drop(columns = "Sales")

In [13]:
X.head(2)

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1

In [8]:
scaler = StandardScaler()

In [14]:
arr = scaler.fit_transform(X)

In [15]:
arr

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

In [16]:
arr.shape

(200, 3)

In [17]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

[1.0046107849396502, 1.1449519171055356, 1.1451873787239286]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(arr, Y, test_size=0.20, random_state=45)

In [19]:
x_train

array([[ 4.42057396e-01, -1.52873340e-01, -3.93756133e-01],
       [ 8.79940308e-01, -1.34128800e+00, -8.03439274e-01],
       [-1.21489154e+00,  1.77992105e-01, -4.62803854e-01],
       [-9.04082253e-02, -5.91776482e-01, -9.36931533e-01],
       [ 1.51633014e+00,  1.73103399e+00,  5.17673775e-01],
       [-9.15759131e-02, -6.05281194e-01, -2.28041604e-01],
       [-1.15300409e+00,  1.60273923e+00, -1.01518562e+00],
       [-8.92609721e-01, -4.90491142e-01,  4.71641962e-01],
       [ 1.33417085e+00,  1.31238792e+00,  1.11148417e+00],
       [-9.18298852e-01,  1.43393033e+00,  2.32276531e-01],
       [ 1.64127273e+00,  1.33264499e+00,  1.89862818e+00],
       [ 1.24659427e+00, -1.32616272e-01, -2.55016247e-02],
       [ 1.18353913e+00,  4.68343414e-01, -4.72010216e-01],
       [ 6.97781017e-01, -1.21974559e+00, -5.13438849e-01],
       [-1.21372386e+00,  2.32010953e-01,  2.09260624e-01],
       [-3.62479475e-01, -1.05093669e+00, -3.43121138e-01],
       [-8.80728498e-02, -1.42906863e+00

In [20]:
x_test

array([[ 0.327624  , -0.051588  ,  0.0435461 ],
       [-1.40405696,  0.65740938, -0.51804203],
       [ 0.64757044, -0.06509271,  0.04814928],
       [ 0.74448853,  1.77830048,  0.32894334],
       [ 1.35285385, -1.33453565, -0.50883567],
       [-0.57850171, -1.05768905, -1.07502697],
       [ 0.28325186,  1.10981724,  0.32894334],
       [-0.82488383,  0.23201095, -0.37994659],
       [ 0.05204968,  1.21785493,  1.28640506],
       [-1.42390765,  0.16448739,  0.5867215 ],
       [-1.2861205 ,  1.03554132,  1.61323094],
       [-1.19504085,  0.17123975, -0.45820067],
       [ 0.24938891, -1.09145083, -0.81724882],
       [ 1.38438142, -0.2203969 , -1.39264649],
       [ 1.07727954, -0.52425292, -0.14978752],
       [-1.06075676, -1.18598381, -0.03931117],
       [ 0.33463012, -0.53100528, -1.29597968],
       [-1.02105537, -0.76058538,  0.57751513],
       [ 0.81454979,  1.39341619, -0.1543907 ],
       [-1.25576062,  1.20435022, -1.13947151],
       [ 0.84958043,  0.69117116,  0.669

In [21]:
Lr = LinearRegression()

In [22]:
Lr.fit(x_train,y_train)

LinearRegression()

In [23]:
Lr.intercept_

15.141271739007381

In [24]:
Lr.coef_


array([ 4.7791721 ,  1.60661382, -0.09323961])

In [25]:
Lr.score(x_test,y_test)

0.8495077592917369

In [26]:
Lr.score(x_train, y_train)

0.910413637900632

In [27]:
# Let's create a function for adjusted r2 for test data set
def adj1_r2(x,y):
    r2 = Lr.score(x_test, y_test)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = (1-(1-r2)*(n-1)/(n-p-1))
    return adjusted_r2

In [28]:
adj1_r2(x_test, y_test)

0.836966739232715

In [29]:
lassocv = LassoCV(alphas=None, cv = 10, max_iter=100000, normalize=True)
lassocv.fit(x_train,y_train)

LassoCV(cv=10, max_iter=100000, normalize=True)

In [30]:
lassocv.alpha_

0.006819044870595716

In [31]:
lasso = Lasso(alpha=lassocv.alpha_)

In [32]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.006819044870595716)

In [33]:
lasso.score(x_train, y_train)

0.9104070974004042

In [34]:
lasso.score(x_test, y_test)

0.8503192687937878

In [37]:
ridgecv = RidgeCV(alphas=np.random.uniform(0,10,50), cv = 10, normalize=True)
ridgecv.fit(x_train, y_train)

RidgeCV(alphas=array([8.30461674, 2.81648521, 5.99973247, 6.96272504, 8.90813002,
       3.20157708, 4.37174093, 5.9009842 , 0.30056376, 0.80913996,
       1.28306086, 7.88964601, 4.00204495, 6.41869243, 6.91884411,
       3.9074701 , 6.12232237, 2.38743793, 3.02504476, 6.26854519,
       1.66847786, 9.89222186, 3.16431829, 5.12210156, 3.45133786,
       5.41775041, 4.59552051, 5.64382163, 9.25145481, 2.62919071,
       7.46358664, 1.72950861, 8.9409042 , 4.64035569, 5.2601119 ,
       1.19254676, 1.93879684, 3.47764144, 7.18627202, 9.25393438,
       7.43667164, 0.35393497, 2.55238941, 1.79145497, 9.81913111,
       2.58040023, 9.48702644, 3.43859825, 4.32722217, 8.74157231]),
        cv=10, normalize=True)

In [38]:
ridgecv.alpha_

0.3005637620431345

In [39]:
ridge = Ridge(alpha=ridgecv.alpha_)

In [41]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.3005637620431345)

In [42]:
ridge.score(x_train, y_train)

0.9104106462093954

In [43]:
ridge.score(x_test, y_test)

0.8500719663972479

In [44]:
elasticcv = ElasticNetCV(alphas=None, cv = 10)
elasticcv.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [45]:
elasticcv.alpha_

0.010000088666847545

In [46]:
elasticcv.l1_ratio

0.5

In [47]:
elastic = ElasticNet(alpha=elasticcv.alpha_, l1_ratio=elasticcv.l1_ratio)

In [48]:
elastic.fit(x_train,y_train)

ElasticNet(alpha=0.010000088666847545)

In [49]:
elastic.score(x_train, y_train)

0.9103764911812797

In [50]:
elastic.score(x_test, y_test)

0.851558228733401

In [51]:
X1 = df[["TV", "Radio"]]

In [52]:
X1.head(1)

TV  Radio
0  230.1   37.8

In [53]:
Y1 = df["Sales"]

In [54]:
Y1.head(1)

0    22.1
Name: Sales, dtype: float64

In [58]:
a1 = scaler.fit_transform(X1)

In [59]:
a1

array([[ 0.96985227,  0.98152247],
       [-1.19737623,  1.08280781],
       [-1.51615499,  1.52846331],
       [ 0.05204968,  1.21785493],
       [ 0.3941822 , -0.84161366],
       [-1.61540845,  1.73103399],
       [-1.04557682,  0.64390467],
       [-0.31343659, -0.24740632],
       [-1.61657614, -1.42906863],
       [ 0.61604287, -1.39530685],
       [-0.94515567, -1.17923146],
       [ 0.79002835,  0.04969734],
       [-1.4390876 ,  0.79920886],
       [-0.57850171, -1.05768905],
       [ 0.66625345,  0.65065703],
       [ 0.56466461,  1.65000572],
       [-0.92530498,  0.9004942 ],
       [ 1.56887609,  1.10306488],
       [-0.90895735, -0.18663512],
       [ 0.0030068 ,  0.04294498],
       [ 0.8332328 ,  0.29953451],
       [ 1.05509347, -1.22649795],
       [-1.5628625 , -0.4972435 ],
       [ 0.94883389, -0.42971994],
       [-0.98952781, -0.72007125],
       [ 1.35285385, -1.33453565],
       [-0.04837147,  0.40757221],
       [ 1.08662104, -0.44322465],
       [ 1.18820988,

In [60]:
x_train, x_test, y_train, y_test = train_test_split(a1, Y1, test_size=0.15, random_state=29)

In [61]:
x_train

array([[-1.39588315, -1.46283041],
       [-0.59368165, -0.57151941],
       [-0.84473452,  1.76479577],
       [-1.58037782,  0.92075127],
       [-0.80386545,  1.58923451],
       [-1.63175608,  0.32654394],
       [-0.85991446, -0.42296758],
       [ 0.77484841,  0.09021148],
       [ 0.47592034, -0.14612098],
       [-0.09157591, -0.60528119],
       [-1.51615499,  1.52846331],
       [-0.91829885,  1.43393033],
       [ 0.67676264,  1.47444446],
       [ 1.39956136,  1.38666383],
       [ 1.60273904, -0.85511837],
       [-1.50798117,  0.96801776],
       [ 0.19217221,  0.91399891],
       [-1.49863967, -0.75383303],
       [ 1.18820988,  0.25902038],
       [ 1.08311798, -1.29402151],
       [-0.61703541, -1.24000266],
       [-1.09228433, -1.43582099],
       [-0.08807285, -1.42906863],
       [-0.36247947, -1.05093669],
       [-1.48813048, -0.21364454],
       [ 1.18353913,  0.46834341],
       [ 0.93598932, -0.50399585],
       [-0.31343659, -0.24740632],
       [-0.7805117 ,

In [62]:
y_train

76      6.9
144    12.3
37     14.7
158     7.3
114    14.6
       ... 
105    15.0
96     16.7
40     16.6
34     11.9
115    12.6
Name: Sales, Length: 170, dtype: float64

In [63]:
x_test

array([[-0.07873135, -1.44257334],
       [ 0.34981006, -0.942899  ],
       [-1.51965805,  1.37991148],
       [-1.49046586, -0.49049114],
       [ 0.54481392,  0.81946593],
       [-0.68592899,  0.15098268],
       [ 1.33417085,  1.31238792],
       [-1.61657614, -1.42906863],
       [ 1.64127273,  1.33264499],
       [-1.21489154,  0.1779921 ],
       [-1.15300409,  1.60273923],
       [ 1.59456522,  1.26512143],
       [ 0.85541887,  1.73778635],
       [ 0.41520058,  1.54872038],
       [ 1.74402926,  0.88023713],
       [ 1.08662104, -0.44322465],
       [ 1.02123053, -1.341288  ],
       [-1.62591764,  1.05579839],
       [-0.71628887,  0.84647535],
       [-0.51778195,  0.42782928],
       [ 1.47896413,  0.38056279],
       [-0.62053847,  1.36640677],
       [ 1.21273132,  0.89374184],
       [ 1.66579418,  1.28537849],
       [ 0.327624  , -0.051588  ],
       [ 1.35285385, -1.33453565],
       [ 0.60786906,  0.49535284],
       [-0.43487612,  1.65675807],
       [ 1.37971067,

In [64]:
Lr2 = LinearRegression()

In [65]:
Lr2.fit(x_train, y_train)

LinearRegression()

In [66]:
Lr2.score(x_train, y_train)

0.8882484266185785

In [67]:
Lr2.score(x_test, y_test)

0.9498661138918756

In [68]:
lassocv = LassoCV(alphas=None, cv = 10, max_iter=10000, normalize=True)

In [69]:
lassocv.fit(x_train,y_train)

LassoCV(cv=10, max_iter=10000, normalize=True)

In [70]:
lassocv.alpha_

0.0003503759662618142

In [71]:
lasso = Lasso(alpha=lassocv.alpha_)

In [73]:
lasso.fit(x_train, y_train)

Lasso(alpha=0.0003503759662618142)

In [74]:
lasso.score(x_train, y_train)

0.8882484170371953

In [75]:
lasso.score(x_test, y_test)

0.9498453143068667

In [76]:
ridgecv = RidgeCV(alphas=np.random.uniform(0,10,20), cv = 10, normalize=True)

In [77]:
ridgecv.fit(x_train, y_train)

RidgeCV(alphas=array([5.64028758, 9.50909242, 7.93536774, 0.51905316, 1.16555321,
       5.01380444, 7.44277475, 2.31543241, 8.05699192, 4.2553447 ,
       5.4686219 , 8.49366809, 2.45154347, 0.39236476, 7.17848414,
       4.83674325, 7.01568808, 3.03398281, 3.19194299, 0.61926321]),
        cv=10, normalize=True)

In [78]:
ridgecv.alpha_

0.39236475599471965

In [79]:
ridge = Ridge(alpha=ridgecv.alpha_)

In [80]:
ridge.fit(x_train, y_train)

Ridge(alpha=0.39236475599471965)

In [81]:
ridge.score(x_train, y_train)

0.8882434415694597

In [82]:
ridge.score(x_test, y_test)

0.9495532212401507

In [83]:
elasticcv = ElasticNetCV(alphas=None, cv = 10)

In [84]:
elasticcv.fit(x_train, y_train)

ElasticNetCV(cv=10)

In [85]:
elasticcv.alpha_

0.00889263632612998

In [86]:
elasticcv.l1_ratio

0.5

In [87]:
elastic = ElasticNet(alpha=elasticcv.alpha_, l1_ratio=elasticcv.l1_ratio)

In [88]:
elastic.fit(x_train, y_train)

ElasticNet(alpha=0.00889263632612998)

In [89]:
elastic.score(x_train, y_train)

0.888219136251759

In [90]:
elastic.score(x_test, y_test)

0.9489813681881145